eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://spring-d2i1:${server.port}/eureka,http://spring-d1i1:${server.port}/eureka,http://spring-d1i2:${server.port}/eureka
